#!/bin/bash

##### Set Color and Icon Files #####

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

##### Set Plugin Directory #####

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####

bar_config=(
    height=35
    color=$BASE
    shadow=on
    position=top
    sticky=on
    padding_right=5
    padding_left=5
    corner_radius=9
    y_offset=5
    margin=5
    blur_radius=20
)

sketchybar --bar "${bar_config[@]}"

##### Setting Defaults #####

default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:16.0"
  label.font="JetBrainsMono Nerd Font:Bold:12.0"
  icon.color=$CRUST
  label.color=$TEXT
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Apple Icon #####

sketchybar --add item logo left \
           --set logo script="$PLUGIN_DIR/apple.sh" \

##### Adding Right Items #####

sketchybar --add item clock right \
           --set clock update_freq=1 script="$PLUGIN_DIR/clock.sh" \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update


### Custom config

# Aerospace workspace integration

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=$SURFACE_2 \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Left Items #####

sketchybar --add item chevron left \
           --set chevron icon= \
           --set chevron icon.font.size=12 \
           --set chevron icon.color=$BLUE \
           --set chevron label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched


